# Generated by Django 3.0.3 on 2020-02-19 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_auto_20200219_2108'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Movie_Links',
            new_name='Movie_Link',
        ),
    ]
