# Generated by Django 3.0.3 on 2020-02-21 15:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0008_movie_movie_trailer'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 21, 15, 33, 11, 867566, tzinfo=utc)),
        ),
    ]
