# Generated by Django 3.0.3 on 2020-03-11 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0011_movie_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='language',
            field=models.CharField(choices=[('english', 'ENGLISH'), ('german', 'GERMAN'), ('arabic', 'ARABIC')], max_length=10),
        ),
    ]
